Imports System.Text.RegularExpressions
Imports Xunit

Public Class TSqlExporterTests

    <Fact>
    Public Sub CreateTable_NoTeComesDobles()
        Dim sql As String = New TSqlExporter().Generar(ProjecteExemple())
        Assert.DoesNotMatch(",\s*,", sql)
        Assert.DoesNotMatch("(?m)^\s*,", sql)
    End Sub

    <Fact>
    Public Sub CreateTable_UsaEsquemaReal()
        Dim p As ProyectoBBDD = ProjecteExemple()
        Dim sql As String = New TSqlExporter().Generar(p)
        Assert.Contains("CREATE TABLE [sales].[CLIENT]", sql)
        Assert.Contains("REFERENCES [sales].[CLIENT]", sql)
        Assert.Contains("@level0name=N'sales'", sql)
        Assert.Contains("CREATE TABLE [dbo].[PRODUCTE]", sql)
        ' L'esquema es crea abans de la primera taula que l'usa
        Dim esq As Integer = sql.IndexOf("IF SCHEMA_ID(N'sales') IS NULL EXEC(N'CREATE SCHEMA [sales]');")
        Assert.True(esq > 0 AndAlso esq < sql.IndexOf("CREATE TABLE [sales].[CLIENT]"))
        Assert.DoesNotContain("CREATE SCHEMA [dbo]", sql)
    End Sub

    <Fact>
    Public Sub PKComposta_IncloTotesLesColumnes()
        Dim sql As String = New TSqlExporter().GenerarTaula(Taula(ProjecteExemple(), "COMANDA_LINIA"))
        Assert.Contains("PRIMARY KEY CLUSTERED ([ID_CLIENT] ASC, [ID_PRODUCTE] ASC)", sql)
    End Sub

    <Fact>
    Public Sub NomsDeDefault_InclouenLaTaula()
        Dim sql As String = New TSqlExporter().Generar(ProjecteExemple())
        Assert.Contains("[DF_CLIENT_DATA_ALTA]", sql)
        Assert.Contains("[DF_PRODUCTE_DATA_ALTA]", sql)
        Assert.DoesNotContain("[DF_DATA_ALTA]", sql)
    End Sub

    <Fact>
    Public Sub Restrict_EsTradueixANoAction()
        Dim sql As String = New TSqlExporter().Generar(ProjecteExemple())
        Assert.DoesNotContain("RESTRICT", sql)
        Assert.Contains("ON DELETE CASCADE", sql)
    End Sub

    <Fact>
    Public Sub SentenciesIndividuals_NoPortenGO()
        Dim p As ProyectoBBDD = ProjecteExemple()
        Dim exp As New TSqlExporter()
        Dim linia As TablaBBDD = Taula(p, "COMANDA_LINIA")
        Assert.DoesNotMatch("(?m)^GO\s*$", exp.GenerarTaula(linia))
        Assert.DoesNotMatch("(?m)^GO\s*$", exp.GenerarAlterFK(p.Relacions(0), linia, Taula(p, "CLIENT")))
        Assert.DoesNotMatch("(?m)^GO\s*$", exp.GenerarExtPropCamp(Taula(p, "CLIENT"), CampDe(Taula(p, "CLIENT"), "NOM")))
    End Sub

    <Fact>
    Public Sub Identificadors_EscapenClaudators()
        Assert.Equal("[a]]b]", TSqlExporter.Q("a]b"))
    End Sub

    <Fact>
    Public Sub AddColumn_NotNullSenseDefault_EsAfegeixNull()
        Dim t As TablaBBDD = Taula(ProjecteExemple(), "PRODUCTE")
        Dim f As CampoBBDD = Camp("CODI", DataType.VarChar, 20, notNull:=True)
        Dim avisos As New List(Of String)()
        Dim sql As String = New TSqlExporter().GenerarAddColumn(t, f, avisos)
        Assert.Equal("ALTER TABLE [dbo].[PRODUCTE] ADD [CODI] VARCHAR(20) NULL;", sql)
        Assert.Single(avisos)
        Assert.True(f.NotNull) ' el model no es modifica
    End Sub

End Class

Public Class MySqlExporterTests

    <Fact>
    Public Sub Genera_PKComposta_IIndexAbansDeFK()
        Dim sql As String = New MySqlExporter().Generar(ProjecteExemple())
        Assert.Contains("PRIMARY KEY (`ID_CLIENT`, `ID_PRODUCTE`)", sql)
        Dim ix As Integer = sql.IndexOf("KEY `IX_COMANDA_LINIA_ID_CLIENT`")
        Dim fk As Integer = sql.IndexOf("CONSTRAINT `FK_COMANDA_LINIA_CLIENT`")
        Assert.True(ix > 0 AndAlso ix < fk)
        Assert.DoesNotContain("CREATE INDEX", sql)
    End Sub

    <Fact>
    Public Sub Defaults_EsTradueixen()
        Dim sql As String = New MySqlExporter().Generar(ProjecteExemple())
        ' DATETIME2 → DATETIME(6): el DEFAULT ha de tenir la mateixa precisió (MySQL 8)
        Assert.Contains("DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)", sql)
        Assert.Contains("DEFAULT 'sense -- nota (cap)'", sql)
        Assert.DoesNotContain("GETDATE", sql)
    End Sub

    <Fact>
    Public Sub Expressions_TradueixenIdentificadorsTSql()
        Dim sql As String = New MySqlExporter().Generar(ProjecteExemple())
        Assert.Contains("CHECK (`PREU` >= 0)", sql)
    End Sub

    <Fact>
    Public Sub SetDefault_EsConverteixIAvisa()
        Dim p As ProyectoBBDD = ProjecteExemple()
        p.Relacions(0).OnDelete = OnDeleteUpdateAction.SetDefault
        Dim sql As String = New MySqlExporter().Generar(p)
        Assert.DoesNotContain("ON DELETE SET DEFAULT", sql)
        Assert.Contains("-- AVÍS:", sql)
    End Sub

End Class

Public Class PostgreSqlExporterTests

    <Fact>
    Public Sub Genera_IdentityBoolIPKComposta()
        Dim sql As String = New PostgreSqlExporter().Generar(ProjecteExemple())
        Assert.Contains("""ID_CLIENT"" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL", sql)
        Assert.Contains("""ACTIU"" BOOLEAN NOT NULL DEFAULT TRUE", sql)
        Assert.Contains("PRIMARY KEY (""ID_CLIENT"", ""ID_PRODUCTE"")", sql)
        Assert.Contains("ON DELETE RESTRICT", sql)
        Assert.DoesNotContain("GETDATE", sql)
    End Sub

    <Fact>
    Public Sub Expressions_CitenLesColumnes()
        Dim p As ProyectoBBDD = ProjecteExemple()
        Dim calc As New CampoBBDD() With {.Nombre = "PREU_IVA", .TipoDato = DataType.DbDecimal,
                                          .Precision = 12, .Escala = 2, .EsCalculado = True,
                                          .FormulaCalculo = "preu * 1.21"}
        Taula(p, "PRODUCTE").Fields.Add(calc)
        Dim sql As String = New PostgreSqlExporter().Generar(p)
        Assert.Contains("CHECK (""PREU"" >= 0)", sql)
        Assert.Contains("GENERATED ALWAYS AS (""PREU"" * 1.21) STORED", sql)
        Assert.Contains("DEFAULT 'sense -- nota (cap)'", sql)
    End Sub

    <Fact>
    Public Sub TipusEspacials_DemanenPostGis()
        Dim p As ProyectoBBDD = ProjecteExemple()
        Taula(p, "CLIENT").Fields.Add(Camp("UBICACIO", DataType.DbGeography))
        Dim sql As String = New PostgreSqlExporter().Generar(p)
        Assert.Contains("CREATE EXTENSION IF NOT EXISTS postgis;", sql)
        Assert.Contains("""UBICACIO"" GEOGRAPHY NULL", sql)
    End Sub

End Class
