Imports Xunit

Public Class SqlScriptImporterTests

    Private Shared Sub ComprovarRoundTrip(sql As String)
        Dim res As SqlScriptImporter.ImportResult = SqlScriptImporter.Importar(sql)
        Assert.Empty(res.Errors)
        Assert.Equal(3, res.Taules.Count)
        Assert.Equal(2, res.Relacions.Count)

        Dim linia As TablaBBDD = res.Taules.Find(Function(t) t.Nombre = "COMANDA_LINIA")
        Assert.Equal(2, linia.PKFields.Count)
        Assert.True(CampDe(linia, "ID_CLIENT").EsFK)
        Assert.True(CampDe(linia, "ID_CLIENT").EsPK)

        Dim client As TablaBBDD = res.Taules.Find(Function(t) t.Nombre = "CLIENT")
        Assert.True(CampDe(client, "ID_CLIENT").EsIdentity)
        Assert.True(CampDe(client, "EMAIL").EsUnique)
        Assert.Equal(100, CampDe(client, "NOM").Longitud)

        Dim prod As TablaBBDD = res.Taules.Find(Function(t) t.Nombre = "PRODUCTE")
        Assert.Equal(10, CampDe(prod, "PREU").Precision)
        Assert.Equal(2, CampDe(prod, "PREU").Escala)
        Assert.False(String.IsNullOrEmpty(CampDe(prod, "PREU").CheckExpression))
        Assert.Contains("sense -- nota (cap)", CampDe(prod, "NOTA").DefaultValue)

        Dim rCli As RelacionBBDD = res.Relacions.Find(Function(r) r.Nombre = "FK_COMANDA_LINIA_CLIENT")
        Assert.Equal(OnDeleteUpdateAction.DoCascade, rCli.OnDelete)
        Assert.Equal(client.Id, rCli.TablaDestinoId)
    End Sub

    <Fact>
    Public Sub RoundTrip_TSql()
        ComprovarRoundTrip(New TSqlExporter().Generar(ProjecteExemple()))
    End Sub

    <Fact>
    Public Sub RoundTrip_MySql()
        ComprovarRoundTrip(New MySqlExporter().Generar(ProjecteExemple()))
    End Sub

    <Fact>
    Public Sub RoundTrip_PostgreSql()
        ComprovarRoundTrip(New PostgreSqlExporter().Generar(ProjecteExemple()))
    End Sub

    <Fact>
    Public Sub Literals_NoEsModifiquen()
        Dim sql As String =
            "CREATE TABLE [T] (" & vbLf &
            "  [ID] INT NOT NULL PRIMARY KEY," & vbLf &
            "  [TXT] VARCHAR(50) DEFAULT ('it''s a TEXT -- not a comment )')," & vbLf &
            "  [TS] TIMESTAMP" & vbLf &
            ");  -- comentari amb 'cometa"
        Dim res As SqlScriptImporter.ImportResult = SqlScriptImporter.Importar(sql)
        Dim t As TablaBBDD = res.Taules(0)
        Assert.Equal(3, t.Fields.Count)
        Assert.Equal("'it''s a TEXT -- not a comment )'", CampDe(t, "TXT").DefaultValue)
        ' A T-SQL, TIMESTAMP és ROWVERSION (no una data)
        Assert.Equal(DataType.RowVersion, CampDe(t, "TS").TipoDato)
    End Sub

    <Fact>
    Public Sub EstilPgDump_PKIdentityIRestriccionsAmbAlterTable()
        Dim sql As String =
            "CREATE TABLE public.""CLIENT"" (""ID_CLIENT"" integer NOT NULL, ""EMAIL"" character varying(200) DEFAULT NULL);" & vbLf &
            "ALTER TABLE public.""CLIENT"" ALTER COLUMN ""ID_CLIENT"" ADD GENERATED BY DEFAULT AS IDENTITY (" & vbLf &
            "    SEQUENCE NAME public.""CLIENT_ID_CLIENT_seq"" START WITH 100 INCREMENT BY 5 NO MINVALUE CACHE 1);" & vbLf &
            "ALTER TABLE ONLY public.""CLIENT"" ADD CONSTRAINT ""PK_CLIENT"" PRIMARY KEY (""ID_CLIENT"");" & vbLf &
            "ALTER TABLE ONLY public.""CLIENT"" ADD CONSTRAINT ""UQ_CLIENT_EMAIL"" UNIQUE (""EMAIL"");"
        Dim res As SqlScriptImporter.ImportResult = SqlScriptImporter.Importar(sql)
        Dim t As TablaBBDD = res.Taules(0)
        Assert.Equal("dbo", t.Schema)
        Dim id As CampoBBDD = CampDe(t, "ID_CLIENT")
        Assert.True(id.EsPK)
        Assert.True(id.EsIdentity)
        Assert.Equal(100, id.IdentitySeed)
        Assert.Equal(5, id.IdentityIncrement)
        Assert.True(CampDe(t, "EMAIL").EsUnique)
        Assert.Equal(200, CampDe(t, "EMAIL").Longitud)
        Assert.Equal("", CampDe(t, "EMAIL").DefaultValue)
    End Sub

    <Fact>
    Public Sub EstilSSMS_DefaultForICheckAmbAlterTable()
        Dim sql As String =
            "CREATE TABLE [dbo].[T]([ID] [int] IDENTITY(1,1) NOT NULL, [QT] [int] NOT NULL," & vbLf &
            " CONSTRAINT [PK_T] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (PAD_INDEX = OFF) ON [PRIMARY]) ON [PRIMARY]" & vbLf &
            "GO" & vbLf &
            "ALTER TABLE [dbo].[T] ADD  CONSTRAINT [DF_T_QT]  DEFAULT ((0)) FOR [QT]" & vbLf &
            "GO" & vbLf &
            "ALTER TABLE [dbo].[T]  WITH CHECK ADD  CONSTRAINT [CK_T_QT] CHECK  (([QT]>=(0)))" & vbLf &
            "GO"
        Dim res As SqlScriptImporter.ImportResult = SqlScriptImporter.Importar(sql)
        Dim t As TablaBBDD = res.Taules(0)
        Assert.True(CampDe(t, "ID").EsPK)
        Assert.Equal("(0)", CampDe(t, "QT").DefaultValue)
        Assert.Equal("([QT]>=(0))", CampDe(t, "QT").CheckExpression)
    End Sub

    <Fact>
    Public Sub FKDeColumna_PostgreSql()
        Dim sql As String =
            "CREATE TABLE pare (id SERIAL PRIMARY KEY);" & vbLf &
            "CREATE TABLE fill (id SERIAL PRIMARY KEY, pare_id INTEGER NOT NULL REFERENCES pare(id) ON DELETE CASCADE, actiu BOOLEAN DEFAULT TRUE);"
        Dim res As SqlScriptImporter.ImportResult = SqlScriptImporter.Importar(sql)
        Assert.Single(res.Relacions)
        Assert.Equal("PARE_ID", res.Relacions(0).CampoFKNombre)
        Assert.Equal(OnDeleteUpdateAction.DoCascade, res.Relacions(0).OnDelete)
        Dim fill As TablaBBDD = res.Taules.Find(Function(t) t.Nombre = "FILL")
        Assert.Equal(DataType.Bit, CampDe(fill, "ACTIU").TipoDato)
        Assert.Equal("1", CampDe(fill, "ACTIU").DefaultValue)
    End Sub

End Class
